language: ruby
bundler_args: --without development non_travis
cache:
  yarn: true
  bundler: true
  directories:
  - node_modules
rvm:
  - 2.4.2
# install yarn
addons:
  apt:
    sources:
      - sourceline: 'deb https://dl.yarnpkg.com/debian/ stable main'
        key_url: 'https://dl.yarnpkg.com/debian/pubkey.gpg'
    packages:
      - yarn
before_install:
  - nvm install 6
  - cp config/database.yml.travis config/database.yml
before_script:
  - RAILS_ENV=test bundle exec rake db:create
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake webpacker:yarn_install
  - RAILS_ENV=test bundle exec rails webpacker:compile
  - RAILS_ENV=test bundle exec rails assets:precompile
script: bundle exec rspec
branches:
  only:
    - master
