development: &default
  adapter: postgresql
  database: kicker_prod
  encoding: utf8
  min_messages: warning
  pool: 5
  timeout: 5000
  host: 127.0.0.1

test:
  <<: *default
  database: kickerapp_test
